name = "cloudinary-signer"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
CLOUDINARY_CLOUD_NAME = "ddp68ttm2"
CLOUDINARY_API_KEY = "942876486665982"

# CLOUDINARY_API_SECRET should be added as a secret:
# Run: npx wrangler secret put CLOUDINARY_API_SECRET
